[mainConfig]
appName = "your app name"
host = "address"
port = 8000

[mysqlConfig]
host = "address"
port = 3306
user = "username"
password = "password"
databaseName = "database"

[redisConfig]
host = "address"
port = 6379
password = ""
db = 0

[authCodeConfig]
accessKeyID = "your accessKeyID in alibaba cloud"
accessKeySecret = "your accessKeySecret in alibaba cloud"
signName = "阿里云短信测试"
templateCode = "SMS_154950909"

[logConfig]
logPath = "./log"

[kafkaConfig]
messageMode = "channel"         # 消息模式 channel or kafka
hostPort = "address:9092"     # "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094" 多个kafka服务器
loginTopic = "login"
chatTopic = "chat_message"
logoutTopic = "logout"
partition = 0 # kafka partition
timeout = 1 # 单位秒

[staticSrcConfig]
staticAvatarPath = "./static/avatars"
staticFilePath = "./static/files"

[EmailConfig]
Email = "your email"
authcode = "your authcode"